SisRh.WEB/Models/ViewModels/SetorViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace SisRh.WEB.Models.ViewModels
{
    public class SetorViewModel
    {
        [Key]
        [Display(ResourceType = typeof(Resources.LabelResource), Name = "LBL_CODIGO")]
        public int Codigo { get; set; }

        [Display(ResourceType = typeof(Resources.LabelResource), Name = "LBL_NOME")]
        public string Nome { get; set; }

        [Display(ResourceType = typeof(Resources.LabelResource), Name = "LBL_SIGLA")]
        public string Sigla { get; set; }

    }
}

SisRh.WEB/Controllers/SetorController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SisRh.Domain.Entities;
using SisRh.Domain.Interfaces.Services;
using SisRh.WEB.Models.Util;
using SisRh.WEB.Models.ViewModels;
using System.Collections.Generic;

namespace SisRh.WEB.Controllers
{
    public class SetorController : ControllerConfig
    {
        private readonly ISetorService _setorService;

        public SetorController(ISetorService setorService ,IMapper mapper)
            :base(mapper)
        {
            _setorService = setorService;
        }

        public IActionResult Index()
        {
            return View(this._mapper.Map<IEnumerable<SetorViewModel>>(_setorService.GetAll()));
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SetorViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            _setorService.Add(this._mapper.Map<Setor>(model));

            if (_setorService.OperacaoValida())
            {
                this.Sucesso = Resources.MensagemResource.MSG_REGISTRO_INSERIDO_SUCESSO;
                return RedirectToAction("Index");
            }
            
            return View(model);
        }

        public IActionResult Edit(int id)
        {
            var model = this._mapper.Map<SetorViewModel>(_setorService.GetById(id));

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, SetorViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            model.Codigo = id;
            _setorService.Update(this._mapper.Map<Setor>(model));

            if (_setorService.OperacaoValida())
            {
                this.Sucesso = Resources.MensagemResource.MSG_REGISTRO_ATUALIZADO_SUCESSO;
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public IActionResult Delete(int id)
        {
            return View(this._mapper.Map<SetorViewModel>(_setorService.GetById(id)));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var model = _setorService.GetById(id);

            if (model != null)
            {
                _setorService.Remove(model);

                this.Sucesso = Resources.MensagemResource.MSG_REGISTRO_EXCLUIDO_SUCESSO;

                return RedirectToAction("Index");
            }

            return RedirectToAction("Delete");
        }
    }
}

SisRh.WEB/ViewComponents/BotaoDefaultViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SisRh.WEB.Models.Util.Components;

namespace SisRh.WEB.ViewComponents
{
    public class BotaoDefaultViewComponent : ViewComponent
    {
        public BotaoDefaultViewComponent()
        {

        }

        public IViewComponentResult Invoke(BotaoDefault.TiposTela tipoTela, string controllerName)
        {
            return View(new BotaoDefault()
            {
                TipoTela = tipoTela,
                ControllerName = controllerName
            });
        }
    }
}

SisRh.WEB/ViewComponents/SummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SisRh.WEB.ViewComponents
{
    public class SummaryViewComponent : ViewComponent
    {
        public SummaryViewComponent()
        {

        }

        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

SisRh.WEB/Views/Setor/Create.cshtml
@model SetorViewModel

<div class="row">
    <div class="col-md-12 form-group">
        <h2>Inserir um novo Setor</h2>
    </div>
</div>

<form asp-action="Create" asp-controller="Setor" asp-antiforgery="true" method="post">

    <vc:botao-default controller-name="Setor" tipo-tela="Criar"></vc:botao-default>
    <vc:summary />

    <div class="row">
        <div class="col-md-6 form-group">
            <label asp-for="Nome"></label>
            <input class="form-control" asp-for="Nome" type="text" />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="col-md-6 form-group">
            <label asp-for="Sigla"></label>
            <input class="form-control" asp-for="Sigla" type="text" />
            <span asp-validation-for="Sigla" class="text-danger"></span>
        </div>
    </div>
    
</form>

SisRh.WEB/Views/Setor/Delete.cshtml
@model SetorViewModel

<div class="row">
    <div class="col-md-12 form-group">
        <h2>Deseja deletar este item?</h2>
    </div>
</div>

<form method="post" asp-action="Delete" asp-antiforgery="true" asp-controller="Setor">
    
    <vc:botao-default controller-name="Setor" tipo-tela="Deletar"></vc:botao-default>
    <vc:summary />

    <div class="row">
        <div class="col-md-1 form-group">
            <label asp-for="Codigo"></label> @Model.Codigo
        </div>
        <div class="col-md-5 form-group">
            <label asp-for="Nome"></label> @Model.Nome
        </div>
        <div class="col-md-6 form-group">
            <label asp-for="Sigla"></label> @Model.Sigla
        </div>
    </div>
</form>

SisRh.WEB/Views/Setor/Edit.cshtml
@model SetorViewModel

<div class="row">
    <div class="col-md-12 form-group">
        <h2>Atualizar dados do setor</h2>
    </div>
</div>

<form asp-action="Edit" asp-controller="Setor" asp-antiforgery="true" method="post">

    <vc:botao-default controller-name="Setor" tipo-tela="Editar"></vc:botao-default>
    <vc:summary />

    <div class="row">
        <div class="col-md-6 form-group">
            <label asp-for="Nome"></label>
            <input class="form-control" asp-for="Nome" type="text" />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
        <div class="col-md-6 form-group">
            <label asp-for="Sigla"></label>
            <input class="form-control" asp-for="Sigla" type="text" />
            <span asp-validation-for="Sigla" class="text-danger"></span>
        </div>
    </div>
</form>

SisRh.WEB/Views/Setor/Index.cshtml
@model IEnumerable<SetorViewModel>

<div class="row">
    <div class="col-md-12 form-group">
        <h2>Lista de Setores</h2>
    </div>
</div>

<vc:botao-default controller-name="Setor" tipo-tela="Listar"></vc:botao-default>
<vc:summary />

<div class="row">
    <div class="col-md-12 form-group table-responsive">
        <table class="table table-bordered table-hover">
            <tr>
                <th>
                    @LabelResource.LBL_CODIGO
                </th>
                <th>
                    @LabelResource.LBL_NOME
                </th>
                <th>
                    @LabelResource.LBL_SIGLA
                </th>
                <th>
                    @LabelResource.LBL_ACOES
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Codigo
                    </td>
                    <td>
                        @item.Nome
                    </td>
                    <td>
                        @item.Sigla
                    </td>
                    <td>
                        <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Codigo">Editar</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Codigo">Excluir</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>