SisRh.WEB/Models/ViewModels/EmpregadoViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.ComponentModel.DataAnnotations;

namespace SisRh.WEB.Models.ViewModels
{
    public class EmpregadoViewModel
    {
        [Key]
        [Display(ResourceType = typeof(Resources.LabelResource),  Name = "LBL_CODIGO")]
        public int Codigo { get; set; }

        [Display(ResourceType = typeof(Resources.LabelResource), Name = "LBL_NOME")]
        public string Nome { get; set; }

        [Display(ResourceType = typeof(Resources.LabelResource), Name = "LBL_EMAIL")]
        public string Email { get; set; }

        [Display(ResourceType = typeof(Resources.LabelResource), Name = "LBL_CPF")]
        public string Cpf { get; set; }

        [Display(ResourceType = typeof(Resources.LabelResource), Name = "LBL_TEL_RESIDENCIAL")]
        public string TelResidencial { get; set; }

        [Display(ResourceType = typeof(Resources.LabelResource), Name = "LBL_TEL_CELULAR")]
        public string TelCelular { get; set; }

        [Display(ResourceType = typeof(Resources.LabelResource), Name = "LBL_DATA_NASC")]
        public DateTime? DataNasc { get; set; }

        [Display(ResourceType = typeof(Resources.LabelResource), Name = "LBL_SETOR")]
        public int CodSetor { get; set; }

        public virtual SetorViewModel Setor { get; set; }

        public SelectList ListaSetores { get; set; }
    }
}

SisRh.WEB/Controllers/EmpregadoController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SisRh.Domain.Entities;
using SisRh.Domain.Interfaces.Services;
using SisRh.WEB.Models.Util;
using SisRh.WEB.Models.ViewModels;
using System;
using System.Collections.Generic;

namespace SisRh.WEB.Controllers
{
    public class EmpregadoController : ControllerConfig
    {
        private readonly IEmpregadoService _empregadoService;
        private readonly ISetorService _setorService;

        public EmpregadoController(IEmpregadoService empregadoService, ISetorService setorService, IMapper mapper)
            : base(mapper)
        {
            _empregadoService = empregadoService;
            _setorService = setorService;
        }

        private void DataLoading(EmpregadoViewModel model)
        {
            model.ListaSetores = new SelectList(_setorService.GetListToSelect(), "Value", "Text");
        }

        public IActionResult Index()
        {
            return View(this._mapper.Map<IEnumerable<EmpregadoViewModel>>(_empregadoService.GetAll()));
        }

        public IActionResult Create()
        {
            EmpregadoViewModel model = new EmpregadoViewModel();
            DataLoading(model);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EmpregadoViewModel model)
        {
            try
            {
                DataLoading(model);

                if (!ModelState.IsValid)
                    return View(model);
                
                _empregadoService.Add(this._mapper.Map<Empregado>(model));

                if (_empregadoService.OperacaoValida())
                {
                    this.Sucesso = Resources.MensagemResource.MSG_REGISTRO_INSERIDO_SUCESSO;
                    return RedirectToAction("Index");
                }

                Funcoes.MontaMensagemErro(ModelState, _empregadoService.GetListaMensagensValidation());
                return View(model);
            }
            catch (Exception ex)
            {
                return View(model);
            }          
        }

        public IActionResult Edit(int id)
        {
            var model = this._mapper.Map<EmpregadoViewModel>(_empregadoService.GetById(id));
            DataLoading(model);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, EmpregadoViewModel model)
        {
            try
            {
                DataLoading(model);

                if (!ModelState.IsValid)
                    return View(model);

                model.Codigo = id;
                _empregadoService.Update(this._mapper.Map<Empregado>(model));

                if (_empregadoService.OperacaoValida())
                {
                    this.Sucesso = Resources.MensagemResource.MSG_REGISTRO_ATUALIZADO_SUCESSO;
                    return RedirectToAction("Index");
                }

                Funcoes.MontaMensagemErro(ModelState, _empregadoService.GetListaMensagensValidation());
                return View(model);
            }
            catch (Exception ex)
            {
                return View(model);
            }
        }

        public IActionResult Delete(int id)
        {
            return View(this._mapper.Map<EmpregadoViewModel>(_empregadoService.GetById(id)));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            try
            {
                var model = _empregadoService.GetById(id);

                if (model != null)
                {
                    _empregadoService.Remove(model);

                    this.Sucesso = Resources.MensagemResource.MSG_REGISTRO_EXCLUIDO_SUCESSO;

                    return RedirectToAction("Index");
                }

                return RedirectToAction("Delete");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Delete");
            }
        }
    }
}

SisRh.WEB/ViewComponents/BotaoDefaultViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SisRh.WEB.Models.Util.Components;

namespace SisRh.WEB.ViewComponents
{
    public class BotaoDefaultViewComponent : ViewComponent
    {
        public BotaoDefaultViewComponent()
        {

        }

        public IViewComponentResult Invoke(BotaoDefault.TiposTela tipoTela, string controllerName)
        {
            return View(new BotaoDefault()
            {
                TipoTela = tipoTela,
                ControllerName = controllerName
            });
        }
    }
}

SisRh.WEB/ViewComponents/SummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SisRh.WEB.ViewComponents
{
    public class SummaryViewComponent : ViewComponent
    {
        public SummaryViewComponent()
        {

        }

        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

SisRh.WEB/Views/Empregado/Create.cshtml
@model EmpregadoViewModel

<div class="row">
    <div class="col-md-12 form-group">
        <h2>Inserir um novo empregado</h2>
    </div>
</div>

<form asp-action="Create" asp-controller="Empregado" asp-antiforgery="true" method="post">
    
    <vc:botao-default controller-name="Empregado" tipo-tela="Criar"></vc:botao-default>
    <vc:summary />

    <div class="row">
        <div class="col-md-6 form-group">
            <label asp-for="Nome"></label>
            <input class="form-control" asp-for="Nome" type="text"/>
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 form-group">
            <label asp-for="Cpf"></label>
            <input class="form-control" asp-for="Cpf" type="text" />
            <span asp-validation-for="Cpf" class="text-danger"></span>
        </div>
        <div class="col-md-6 form-group">
            <label asp-for="Email"></label>
            <input class="form-control" asp-for="Email" type="text" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 form-group">
            <label asp-for="TelResidencial"></label>
            <input class="form-control" asp-for="TelResidencial" type="text" />
            <span asp-validation-for="TelResidencial" class="text-danger"></span>
        </div>
        <div class="col-md-6 form-group">
            <label asp-for="TelCelular"></label>
            <input class="form-control" asp-for="TelCelular" type="text" />
            <span asp-validation-for="TelCelular" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 form-group">
            <label asp-for="DataNasc"></label>
            <input class="form-control" asp-for="DataNasc" type="text" placeholder="dd/mm/aaaa" />
            <span asp-validation-for="DataNasc" class="text-danger"></span>
        </div>
        <div class="col-md-6 form-group">
            <label asp-for="CodSetor"></label>
            <select asp-for="CodSetor" asp-items="Model.ListaSetores" class="form-control"></select>
            <span asp-validation-for="CodSetor" class="text-danger"></span>
        </div>
    </div>

</form>

SisRh.WEB/Views/Empregado/Delete.cshtml
@model EmpregadoViewModel

<div class="row">
    <div class="col-md-12 form-group">
        <h2>Deseja deletar este item?</h2>
    </div>
</div>

<form method="post" asp-action="Delete" asp-antiforgery="true" asp-controller="Empregado">
    <vc:botao-default controller-name="Empregado" tipo-tela="Deletar"></vc:botao-default>
    <vc:summary />

    <div class="row">
        <div class="col-md-1 form-group">
            <label asp-for="Codigo"></label> @Model.Codigo
        </div>
        <div class="col-md-5 form-group">
            <label asp-for="Nome"></label> @Model.Nome
        </div>
        <div class="col-md-2 form-group">
            <label asp-for="Cpf"></label> @Model.Cpf
        </div>
        <div class="col-md-4 form-group">
            <label asp-for="Email"></label> @Model.Email
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 form-group">
            <label asp-for="TelResidencial"></label> @Model.TelResidencial
        </div>
        <div class="col-md-6 form-group">
            <label asp-for="TelCelular"></label> @Model.TelCelular
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 form-group">
            <label asp-for="DataNasc"></label> @Model.DataNasc
        </div>
    </div>
</form>

SisRh.WEB/Views/Empregado/Edit.cshtml
@model EmpregadoViewModel

<div class="row">
    <div class="col-md-12 form-group">
        <h2>Atualizar dados do empregado</h2>
    </div>
</div>

<form asp-action="Edit" asp-controller="Empregado" asp-antiforgery="true" method="post">

    <vc:botao-default controller-name="Empregado" tipo-tela="Editar"></vc:botao-default>

    <vc:summary />

    <div class="row">
        <div class="col-md-6 form-group">
            <label asp-for="Nome"></label>
            <input class="form-control" asp-for="Nome" type="text" />
            <span asp-validation-for="Nome" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 form-group">
            <label asp-for="Cpf"></label>
            <input class="form-control" asp-for="Cpf" type="text" />
            <span asp-validation-for="Cpf" class="text-danger"></span>
        </div>
        <div class="col-md-6 form-group">
            <label asp-for="Email"></label>
            <input class="form-control" asp-for="Email" type="text" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 form-group">
            <label asp-for="TelResidencial"></label>
            <input class="form-control" asp-for="TelResidencial" type="text" />
            <span asp-validation-for="TelResidencial" class="text-danger"></span>
        </div>
        <div class="col-md-6 form-group">
            <label asp-for="TelCelular"></label>
            <input class="form-control" asp-for="TelCelular" type="text" />
            <span asp-validation-for="TelCelular" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 form-group">
            <label asp-for="DataNasc"></label>
            <input class="form-control" asp-for="DataNasc" type="text" placeholder="dd/mm/aaaa" />
            <span asp-validation-for="DataNasc" class="text-danger"></span>
        </div>
        <div class="col-md-6 form-group">
            <label asp-for="CodSetor"></label>
            <select asp-for="CodSetor" asp-items="Model.ListaSetores" class="form-control"></select>
            <span asp-validation-for="CodSetor" class="text-danger"></span>
        </div>
    </div>

</form>

SisRh.WEB/Views/Empregado/Index.cshtml
@model IEnumerable<EmpregadoViewModel>

<div class="row">
    <div class="col-md-12 form-group">
        <h2>Lista de Empregados</h2>
    </div>
</div>

<vc:botao-default controller-name="Empregado" tipo-tela="Listar"></vc:botao-default>
<vc:summary />

<div class="row">
    <div class="col-md-12 form-group table-responsive">
        <table class="table table-bordered table-hover">
            <tr>
                <th>
                    @LabelResource.LBL_CODIGO
                </th>
                <th>
                    @LabelResource.LBL_NOME
                </th>
                <th>
                    @LabelResource.LBL_CPF
                </th>
                <th>
                    @LabelResource.LBL_EMAIL
                </th>
                <th>
                    @LabelResource.LBL_TEL_RESIDENCIAL
                </th>
                <th>
                    @LabelResource.LBL_TEL_CELULAR
                </th>
                <th>
                    @LabelResource.LBL_DATA_NASC
                </th>
                <th>
                    @LabelResource.LBL_SETOR
                </th>
                <th>
                    @LabelResource.LBL_ACOES
                </th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.Codigo
                    </td>
                    <td>
                        @item.Nome
                    </td>
                    <td>
                        @item.Cpf
                    </td>
                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.TelResidencial
                    </td>
                    <td>
                        @item.TelCelular
                    </td>
                    <td>
                        @item.DataNasc
                    </td>
                    <td>
                        @item.Setor.Nome
                    </td>
                    <td>
                        <a class="btn btn-primary" asp-action="Edit"  asp-route-id="@item.Codigo">Editar</a>
                        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Codigo">Excluir</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>